-- 1. Create the waitlist Table (all lowercase)
create table public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null unique,
  phone text,
  jamb_candidate boolean default false not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.waitlist enable row level security;

-- 3. Create a Policy to allow public inserts
create policy "Allow public insert on waitlist"
on public.waitlist
for insert
with check (true);
