-- 1. Ensure Table Exists with unique email constraint
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null unique,
  phone text,
  jamb_candidate boolean default false not null
);

-- 2. Deduplication & Unique Constraint Migration (Run in Supabase SQL Editor if needed)
-- Remove existing duplicates, keeping only the earliest/original record per email:
-- DELETE FROM public.waitlist w1
-- USING public.waitlist w2
-- WHERE LOWER(TRIM(w1.email)) = LOWER(TRIM(w2.email))
--   AND (
--     w1.created_at > w2.created_at 
--     OR (w1.created_at = w2.created_at AND w1.id > w2.id)
--   );

-- Normalize existing emails to lowercase trimmed format:
-- UPDATE public.waitlist SET email = LOWER(TRIM(email));

-- Enforce case-insensitive unique index & constraint:
-- DROP INDEX IF EXISTS waitlist_email_lower_idx;
-- CREATE UNIQUE INDEX waitlist_email_lower_idx ON public.waitlist (LOWER(TRIM(email)));

-- 3. Enable Row Level Security (RLS)
alter table public.waitlist enable row level security;

-- 4. Drop existing public policies to clean up permissions
drop policy if exists "Allow public insert on waitlist" on public.waitlist;
drop policy if exists "Allow public select on waitlist" on public.waitlist;
drop policy if exists "Allow public update on waitlist" on public.waitlist;
drop policy if exists "Allow public delete on waitlist" on public.waitlist;

-- 5. Create policy to allow public INSERTS ONLY
create policy "Allow public insert on waitlist"
on public.waitlist
for insert
to anon, authenticated
with check (true);

-- 6. Secure RPC Function: Returns count of UNIQUE registered emails
create or replace function public.get_waitlist_count()
returns integer
language sql
security definer
set search_path = public
as $$
  select count(distinct lower(trim(email)))::integer from public.waitlist;
$$;

-- 7. Grant execute privilege to public anonymous visitors
grant execute on function public.get_waitlist_count() to anon, authenticated, service_role;



