-- 1. Ensure Table Exists
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null unique,
  phone text,
  jamb_candidate boolean default false not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.waitlist enable row level security;

-- 3. Drop existing public policies to clean up permissions
drop policy if exists "Allow public insert on waitlist" on public.waitlist;
drop policy if exists "Allow public select on waitlist" on public.waitlist;
drop policy if exists "Allow public update on waitlist" on public.waitlist;
drop policy if exists "Allow public delete on waitlist" on public.waitlist;

-- 4. Create policy to allow public INSERTS ONLY
create policy "Allow public insert on waitlist"
on public.waitlist
for insert
to anon, authenticated
with check (true);

-- 5. Secure RPC Function: Returns ONLY total integer count without exposing rows or PII
create or replace function public.get_waitlist_count()
returns integer
language sql
security definer
set search_path = public
as $$
  select count(*)::integer from public.waitlist;
$$;

-- 6. Grant execute privilege to public anonymous visitors
grant execute on function public.get_waitlist_count() to anon, authenticated, service_role;


